version: 2
jobs:

  build:
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/react-circle-ci
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          key: v2-dependency-cache-{{ checksum "package.json" }}

      # - run:
      #     name: Remove the node_modules
      #     command: rm -rf node_modules
      #
      # - run:
      #     name: Clean the cache for the noe modules
      #     command: npm cache clean --force

      - run:
          name: Install npm dependencies
          command: npm install

      - save_cache:
          key: v2-dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  test:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/react-circle-ci
    steps:
      - checkout
      #
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "package.json" }}

      # - run:
      #     name: Remove the node_modules
      #     command: rm -rf node_modules
      #
      # - run:
      #     name: Clean the cache for the noe modules
      #     command: npm cache clean --force

      - run:
          name: Install npm dependencies
          command: npm install

      - save_cache:
          key: v2-dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Install mocha globally
          command: sudo npm install mocha -g

      # - run:
      #     name: Run the app
      #     command: npm run start

      - run:
          name: Test chromedriver
          command: mocha selenium.js

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
